const htmlEscape = (v) => String(v).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');
function formatValue(value) {
  if (value === null || value === undefined) return '—';
  if (typeof value === 'number') { const a = Math.abs(value); if ((a !== 0 && a < 0.001) || a >= 1e5) return value.toExponential(5); return Number.isInteger(value) ? String(value) : value.toPrecision(6).replace(/\.?0+$/, ''); }
  return String(value);
}
function makeInput(def, value) {
  if (def.type === 'derived') return `<output class="control-output" data-output="${htmlEscape(def.id)}">${htmlEscape(formatValue(value))}</output>`;
  if (def.type === 'categorical') {
    if (def.options?.every((v) => typeof v === 'boolean')) return `<label class="switch"><input data-control="${htmlEscape(def.id)}" type="checkbox" ${value ? 'checked' : ''}><span></span></label>`;
    return `<select data-control="${htmlEscape(def.id)}">${(def.options || []).map((opt) => `<option value="${htmlEscape(opt)}" ${Object.is(opt, value) ? 'selected' : ''}>${htmlEscape(opt)}</option>`).join('')}</select>`;
  }
  return `<div class="range-pair"><input data-control="${htmlEscape(def.id)}" type="range" min="${def.min}" max="${def.max}" step="${def.step ?? 'any'}" value="${value}"><input data-number="${htmlEscape(def.id)}" type="number" min="${def.min ?? ''}" max="${def.max ?? ''}" step="${def.step ?? 'any'}" value="${value}"></div>`;
}
export function mountControlBoard({ root, definitions, graph, onBegin, onInput, onCommit, onTrace }) {
  const grouped = new Map();
  for (const def of definitions) { const theory = def.theoryId || 'UNSCOPED'; const sector = def.sector || 'Controls'; if (!grouped.has(theory)) grouped.set(theory, new Map()); const sectors = grouped.get(theory); if (!sectors.has(sector)) sectors.set(sector, []); sectors.get(sector).push(def); }
  root.innerHTML = [...grouped.entries()].map(([theory, sectors], theoryIndex) => `<details class="theory-group" ${theoryIndex === 0 ? 'open' : ''}><summary><span>${htmlEscape(theory)}</span><small>${[...sectors.values()].flat().length} controls</small></summary>${[...sectors.entries()].map(([sector, defs]) => `<details class="sector-group" open><summary><span>${htmlEscape(sector)}</span><small>${defs.length}</small></summary><div class="sector-controls">${defs.map((def) => { const value = graph.get(def.id); const deps = (def.dependencies || []).join(' ← '); return `<article class="control-row ${def.type === 'derived' ? 'is-derived' : ''}" data-control-row="${htmlEscape(def.id)}"><header><button class="trace-button" type="button" data-trace="${htmlEscape(def.id)}" title="Trace dependency">↳</button><div><strong>${htmlEscape(def.label)}</strong><code>${htmlEscape(def.symbol || def.id)}</code></div><span class="type-tag">${htmlEscape(def.type.toUpperCase())}</span></header><div class="control-widget">${makeInput(def, value)}</div><footer><span>${htmlEscape(def.authorityStatus || '')}</span><span>${htmlEscape(def.units || '')}</span>${deps ? `<span class="deps" title="${htmlEscape(deps)}">deps ${htmlEscape(String((def.dependencies || []).length))}</span>` : ''}</footer></article>`; }).join('')}</div></details>`).join('')}</details>`).join('');
  const readValue = (el, def) => { if (el.type === 'checkbox') return el.checked; if (def.type === 'categorical') return el.value; return Number(el.value); };
  const begin = (id) => onBegin?.(id);
  root.querySelectorAll('[data-control]').forEach((el) => { const id = el.dataset.control; const def = definitions.find((d) => d.id === id); el.addEventListener('pointerdown', () => begin(id)); el.addEventListener('focus', () => begin(id)); el.addEventListener('input', () => { const value = readValue(el, def); const number = root.querySelector(`[data-number="${CSS.escape(id)}"]`); if (number && number !== el) number.value = String(value); onInput?.(id, value); }); el.addEventListener('change', () => onCommit?.(id, readValue(el, def))); });
  root.querySelectorAll('[data-number]').forEach((el) => { const id = el.dataset.number; el.addEventListener('focus', () => begin(id)); el.addEventListener('input', () => { const value = Number(el.value); const range = root.querySelector(`[data-control="${CSS.escape(id)}"]`); if (range) range.value = String(value); onInput?.(id, value); }); el.addEventListener('change', () => onCommit?.(id, Number(el.value))); });
  root.querySelectorAll('[data-trace]').forEach((button) => button.addEventListener('click', () => onTrace?.(button.dataset.trace)));
  return { refresh(state) { for (const def of definitions) { const value = state[def.id]; const out = root.querySelector(`[data-output="${CSS.escape(def.id)}"]`); if (out) out.textContent = formatValue(value); const input = root.querySelector(`[data-control="${CSS.escape(def.id)}"]`); if (input && document.activeElement !== input) { if (input.type === 'checkbox') input.checked = Boolean(value); else input.value = String(value ?? ''); } const number = root.querySelector(`[data-number="${CSS.escape(def.id)}"]`); if (number && document.activeElement !== number) number.value = String(value ?? ''); } } };
}
export function renderDependencyTrace(root, id, definitions, state) {
  const map = new Map(definitions.map((d) => [d.id, d])); const def = map.get(id); if (!def) return;
  const dependents = definitions.filter((d) => (d.dependencies || []).includes(id)); const dependencies = (def.dependencies || []).map((dep) => map.get(dep)).filter(Boolean);
  root.innerHTML = `<div class="trace-title"><code>${htmlEscape(id)}</code><span>${htmlEscape(def.authorityStatus || '')}</span></div><p>${htmlEscape(def.description || 'Typed control in the current dependency graph.')}</p><div class="trace-columns"><section><h4>UPSTREAM</h4>${dependencies.length ? dependencies.map((d) => `<div>${htmlEscape(d.id)} <b>${htmlEscape(formatValue(state[d.id]))}</b></div>`).join('') : '<em>none</em>'}</section><section><h4>CURRENT</h4><div>${htmlEscape(def.symbol || id)} <b>${htmlEscape(formatValue(state[id]))}</b></div></section><section><h4>DOWNSTREAM</h4>${dependents.length ? dependents.map((d) => `<div>${htmlEscape(d.id)} <b>${htmlEscape(formatValue(state[d.id]))}</b></div>`).join('') : '<em>none</em>'}</section></div>`;
}
